[package]
name = "pubmed-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
entrez-rs = "0.1.4"
quick-xml = "0.31.0"
xml-rs = "0.8.19"
